//@ts-check
import { BlockPermutation, EquipmentSlot, GameMode, system } from "@minecraft/server";
import { BlockList, Manager, StateBlock } from "./classes.js";
import { damage_item } from "./functions.js";

/**@typedef {import('./classes.js').States}States*/
/**@typedef {import('@minecraft/server').Block}Block*/

export const CHISEL_BLOCKS = new Manager([
  new BlockList([
    "minecraft:redstone_lamp",
    new StateBlock("aga_chisel:redstone_lamp_square", {
      "redstone:active": false,
    }),
  ], 'tile.redstone_lamp.name'),
  new BlockList([
    "minecraft:lit_redstone_lamp",
    new StateBlock("aga_chisel:redstone_lamp_square", {
      "redstone:active": true,
    }),
  ], 'tile.lit_redstone_lamp.name'),
  new BlockList([
    "minecraft:stone_bricks",
    "minecraft:cracked_stone_bricks",
    "minecraft:chiseled_stone_bricks",
    "aga_chisel:stone_braid",
    "aga_chisel:stone_chaotic_medium",
    "aga_chisel:stone_chaotic_small",
    "aga_chisel:stone_circular",
    "aga_chisel:stone_cracked_bricks",
    "aga_chisel:stone_cracked",
    "aga_chisel:stone_cuts",
    "aga_chisel:stone_dent",
    "aga_chisel:stone_encased_bricks",
    "aga_chisel:stone_french_1",
    "aga_chisel:stone_french_2",
    "aga_chisel:stone_largeornate",
    "aga_chisel:stone_layer",
    "aga_chisel:stone_mosaic",
    "aga_chisel:stone_ornate",
    "aga_chisel:stone_panel",
    "aga_chisel:stone_pillar",
    "aga_chisel:stone_poison",
    "aga_chisel:stone_prism",
    "aga_chisel:stone_raw",
    "aga_chisel:stone_road",
    "aga_chisel:stone_small_brick",
    "aga_chisel:stone_soft_bricks",
    "aga_chisel:stone_solid_bricks",
    "aga_chisel:stone_sunken",
    "aga_chisel:stone_tiles_large",
    "aga_chisel:stone_tiles_medium",
    "aga_chisel:stone_tiles_small",
    "aga_chisel:stone_triple_bricks",
    "aga_chisel:stone_twisted",
    "aga_chisel:stone_weaver",
  ], "itemGroup.name.stoneBrick"),
  new BlockList([
    "minecraft:brick_block",
    "aga_chisel:bricks_braid",
    "aga_chisel:bricks_chaotic_medium",
    "aga_chisel:bricks_chaotic_small",
    "aga_chisel:bricks_circular",
    "aga_chisel:bricks_cracked_bricks",
    "aga_chisel:bricks_cracked",
    "aga_chisel:bricks_cuts",
    "aga_chisel:bricks_dent",
    "aga_chisel:bricks_encased_bricks",
    "aga_chisel:bricks_french_1",
    "aga_chisel:bricks_french_2",
    "aga_chisel:bricks_layers",
    "aga_chisel:bricks_mosaic",
    "aga_chisel:bricks_ornate",
    "aga_chisel:bricks_panel",
    "aga_chisel:bricks_pillar",
    "aga_chisel:bricks_prism",
    "aga_chisel:bricks_raw",
    "aga_chisel:bricks_road",
    "aga_chisel:bricks_small_brick",
    "aga_chisel:bricks_soft_bricks",
    "aga_chisel:bricks_solid_bricks",
    "aga_chisel:bricks_tiles_large",
    "aga_chisel:bricks_tiles_medium",
    "aga_chisel:bricks_tiles_small",
    "aga_chisel:bricks_triple_bricks",
    "aga_chisel:bricks_weaver",
  ], "tile.brick_block.name"),
  new BlockList([
    "minecraft:coal_block",
    "aga_chisel:coal_braid",
    "aga_chisel:coal_chaotic_medium",
    "aga_chisel:coal_chaotic_medium",
    "aga_chisel:coal_chaotic",
    "aga_chisel:coal_circular",
    "aga_chisel:coal_cracked_bricks",
    "aga_chisel:coal_cracked",
    "aga_chisel:coal_cuts",
    "aga_chisel:coal_dent",
    "aga_chisel:coal_encased_bricks",
    "aga_chisel:coal_french_1",
    "aga_chisel:coal_french_2",
    "aga_chisel:coal_french_alt",
    "aga_chisel:coal_french",
    "aga_chisel:coal_large_bricks",
    "aga_chisel:coal_layers",
    "aga_chisel:coal_masonry",
    "aga_chisel:coal_mosaic",
    "aga_chisel:coal_ornate",
    "aga_chisel:coal_panel",
    "aga_chisel:coal_pillar",
    "aga_chisel:coal_prism",
    "aga_chisel:coal_raw",
    "aga_chisel:coal_road",
    "aga_chisel:coal_small_bricks",
    "aga_chisel:coal_soft_bricks",
    "aga_chisel:coal_tiles_large",
    "aga_chisel:coal_tiles_med",
    "aga_chisel:coal_tiles_medium",
    "aga_chisel:coal_tiles_small",
    "aga_chisel:coal_triple_bricks",
    "aga_chisel:coal_twisted",
    "aga_chisel:coal_weaver",
  ], "tile.coal_block.name"),
  new BlockList([
    "minecraft:copper_block",
    "aga_chisel:copper_badgreggy",
    "aga_chisel:copper_bolted",
    "aga_chisel:copper_caution",
    "aga_chisel:copper_crate",
    "aga_chisel:copper_machine",
    "aga_chisel:copper_scaffold",
    "aga_chisel:copper_thermal",
  ], "tile.copper_block.name"),
  new BlockList([
    "minecraft:diamond_block",
    "aga_chisel:diamond_bismuth",
    "aga_chisel:diamond_cells",
    "aga_chisel:diamond_crushed",
    "aga_chisel:diamond_embossed",
    "aga_chisel:diamond_four_ornate",
    "aga_chisel:diamond_four",
    "aga_chisel:diamond_gem",
    "aga_chisel:diamond_ornate_layer",
    "aga_chisel:diamond_simple",
    "aga_chisel:diamond_space_black",
    "aga_chisel:diamond_space",
    "aga_chisel:diamond_zelda",
  ], "tile.diamond_block.name"),
  new BlockList([
    "minecraft:dirt",
    "aga_chisel:dirt_big_bricks",
    "aga_chisel:dirt_bricks",
    "aga_chisel:dirt_chunky",
    "aga_chisel:dirt_classicbricks",
    "aga_chisel:dirt_cobble",
    "aga_chisel:dirt_happy",
    "aga_chisel:dirt_horizontal",
    "aga_chisel:dirt_layers",
    "aga_chisel:dirt_netherbricks",
    "aga_chisel:dirt_plate",
    "aga_chisel:dirt_reinforced_cobble",
    "aga_chisel:dirt_reinforced",
    "aga_chisel:dirt_vert",
    "aga_chisel:dirt_vertical",
  ], "tile.dirt.name"),
  new BlockList([
    "minecraft:emerald_block",
    "aga_chisel:emerald_cell",
    "aga_chisel:emerald_cellbismuth",
    "aga_chisel:emerald_chunk",
    "aga_chisel:emerald_circle",
    "aga_chisel:emerald_four",
    "aga_chisel:emerald_fourornate",
    "aga_chisel:emerald_goldborder",
    "aga_chisel:emerald_ornate",
    "aga_chisel:emerald_panel",
    "aga_chisel:emerald_panelclassic",
    "aga_chisel:emerald_prismatic",
    "aga_chisel:emerald_smooth",
    "aga_chisel:emerald_zelda",
  ], "tile.emerald_block.name"),
  new BlockList([
    "minecraft:glowstone",
    "aga_chisel:glowstone_bismuth",
    "aga_chisel:glowstone_braid",
    "aga_chisel:glowstone_chaotic_medium",
    "aga_chisel:glowstone_chaotic_small",
    "aga_chisel:glowstone_circular",
    "aga_chisel:glowstone_cracked_bricks",
    "aga_chisel:glowstone_cracked",
    "aga_chisel:glowstone_dent",
    "aga_chisel:glowstone_encased_bricks",
    "aga_chisel:glowstone_french_1",
    "aga_chisel:glowstone_french_2",
    "aga_chisel:glowstone_layers",
    "aga_chisel:glowstone_mosaic",
    "aga_chisel:glowstone_neon_panel",
    "aga_chisel:glowstone_neon",
    "aga_chisel:glowstone_ornate",
    "aga_chisel:glowstone_panel",
    "aga_chisel:glowstone_pillar",
    "aga_chisel:glowstone_prism",
    "aga_chisel:glowstone_road",
    "aga_chisel:glowstone_small_brick",
    "aga_chisel:glowstone_soft_bricks",
    "aga_chisel:glowstone_solid_bricks",
    "aga_chisel:glowstone_tiles_large_bismuth",
    "aga_chisel:glowstone_tiles_large",
    "aga_chisel:glowstone_tiles_medium_bismuth",
    "aga_chisel:glowstone_tiles_medium",
    "aga_chisel:glowstone_tiles_small",
    "aga_chisel:glowstone_triple_bricks",
    "aga_chisel:glowstone_twisted",
  ], "tile.glowstone.name"),
  new BlockList([
    "minecraft:gold_block",
    "aga_chisel:gold_badgreggy",
    "aga_chisel:gold_bolted",
    "aga_chisel:gold_bricks",
    "aga_chisel:gold_cart",
    "aga_chisel:gold_caution",
    "aga_chisel:gold_coin_heads",
    "aga_chisel:gold_coin_tails",
    "aga_chisel:gold_crate_dark",
    "aga_chisel:gold_crate_light",
    "aga_chisel:gold_crate",
    "aga_chisel:gold_eye",
    "aga_chisel:gold_largeingot",
    "aga_chisel:gold_machine",
    "aga_chisel:gold_plates",
    "aga_chisel:gold_rivet",
    "aga_chisel:gold_scaffold",
    "aga_chisel:gold_simple",
    "aga_chisel:gold_smallingot",
    "aga_chisel:gold_space",
    "aga_chisel:gold_spaceblack",
    "aga_chisel:gold_star",
    "aga_chisel:gold_thermal",
  ], "tile.gold_block.name"),
  new BlockList([
    "minecraft:iron_block",
    "aga_chisel:iron_badgreggy",
    "aga_chisel:iron_bolted",
    "aga_chisel:iron_brick",
    "aga_chisel:iron_caution",
    "aga_chisel:iron_coin_heads",
    "aga_chisel:iron_coin_tails",
    "aga_chisel:iron_crate_dark",
    "aga_chisel:iron_crate_light",
    "aga_chisel:iron_crate",
    "aga_chisel:iron_gears",
    "aga_chisel:iron_largeingot",
    "aga_chisel:iron_machine",
    "aga_chisel:iron_moon",
    "aga_chisel:iron_plates",
    "aga_chisel:iron_rivets",
    "aga_chisel:iron_scaffold",
    "aga_chisel:iron_simple",
    "aga_chisel:iron_smallingot",
    "aga_chisel:iron_space",
    "aga_chisel:iron_spaceblack",
    "aga_chisel:iron_thermal",
    "aga_chisel:iron_vents",
  ], "tile.iron_block.name"),
  new BlockList([
    "minecraft:lapis_block",
    "aga_chisel:lapis_chunky",
    "aga_chisel:lapis_ornate",
    "aga_chisel:lapis_ornatelayer",
    "aga_chisel:lapis_panel",
    "aga_chisel:lapis_smooth",
    "aga_chisel:lapis_tile",
    "aga_chisel:lapis_zelda",
  ], "tile.lapis_block.name"),
  new BlockList([
    "minecraft:obsidian",
    "aga_chisel:obsidian_blocks",
    "aga_chisel:obsidian_chiseled",
    "aga_chisel:obsidian_chunks",
    "aga_chisel:obsidian_crate",
    "aga_chisel:obsidian_crystal",
    "aga_chisel:obsidian_greek",
    "aga_chisel:obsidian_growth",
    "aga_chisel:obsidian_map_a",
    "aga_chisel:obsidian_map_b",
    "aga_chisel:obsidian_panel_light",
    "aga_chisel:obsidian_panel_shiny",
    "aga_chisel:obsidian_panel",
    "aga_chisel:obsidian_pillar_quartz",
    "aga_chisel:obsidian_pillar",
    "aga_chisel:obsidian_tiles",
  ], "tile.obsidian.name"),
  new BlockList([
    "minecraft:redstone_block",
    "aga_chisel:redstone_braid",
    "aga_chisel:redstone_chaotic_medium",
    "aga_chisel:redstone_chaotic_small",
    "aga_chisel:redstone_circular",
    "aga_chisel:redstone_cracked_bricks",
    "aga_chisel:redstone_cracked",
    "aga_chisel:redstone_dent",
    "aga_chisel:redstone_encased_bricks",
    "aga_chisel:redstone_french_1",
    "aga_chisel:redstone_french_2",
    "aga_chisel:redstone_layers",
    "aga_chisel:redstone_mosaic",
    "aga_chisel:redstone_ornate",
    "aga_chisel:redstone_panel",
    "aga_chisel:redstone_pillar",
    "aga_chisel:redstone_prism",
    "aga_chisel:redstone_road",
    "aga_chisel:redstone_small_bricks",
    "aga_chisel:redstone_soft_bricks",
    "aga_chisel:redstone_solid_bricks",
    "aga_chisel:redstone_tiles_large",
    "aga_chisel:redstone_tiles_medium",
    "aga_chisel:redstone_tiles_small",
    "aga_chisel:redstone_triple_bricks",
    "aga_chisel:redstone_twisted",
  ], "tile.redstone_block.name"),
]);

/**@param {Block}block@param {States|undefined}states*/
function hasStates(block, states) {
  if (!states) return true;
  const blockStates = block.permutation.getAllStates();
  return Object.entries(states).every((v) => blockStates[v[0]] === v[1]);
}

/**@param {Block}block@param {import('@minecraft/server').ItemStack}item@param {import('@minecraft/server').Player}player*/
export default function chisel(block, item, player) {
  if (!CHISEL_BLOCKS.includes(block)) return false;
  let blockData = /**@type {import('./classes.js').BlockData|null}*/ (null);
  const chisel_data = /**@type {string|undefined}*/(item.getDynamicProperty("aga_chisel:data"));
  if (chisel_data) {
    const id = (/**@type {string[]}*/(JSON.parse(chisel_data))).find((b) =>
      b && CHISEL_BLOCKS.getItemInList(block, b)
    );
    if (id) {
      blockData = BlockList.BlockListItemToData(
        /**@type {import('./classes.js').BlockListItem}*/(CHISEL_BLOCKS.getList(block)?.getItem(id)),
      );
    }
  }
  if (!blockData) blockData = CHISEL_BLOCKS.getNext(block);
  if (!blockData) return;

  const blockId = blockData[0];
  const states = blockData[1];
  if (blockId == block.typeId && hasStates(block, states)) return;
  system.run(() => {
    block.setPermutation(BlockPermutation.resolve(blockId, states));
    block.dimension.playSound("block.stonecutter.use", block.location, {
      pitch: 1.4,
      volume: 0.6,
    });

    if (player.getGameMode() === GameMode.Creative) return;

    const equippement = player.getComponent("equippable");

    const newItem = damage_item(item);
    equippement?.setEquipment(EquipmentSlot.Mainhand, newItem);
    if (!newItem) {
      player.playSound("random.break", {
        volume: 1,
        pitch: 1,
      });
    }
  });
}
